-- ============================================================
-- V11.34.0: md_payment_method/channel 补自增序列
--
-- 背景：
--   erp-finance 实体的 BaseEntity 使用 @TableId(IdType.AUTO)，
--   但 V11.29.0 建表时 id 列是纯 BIGINT 无自增，create 报
--   "null value in column id violates not-null constraint" (400)。
--   方案同 V11.27.0：GENERATED BY DEFAULT AS IDENTITY——
--   兼容 IdType.AUTO（DB 生成）与 IdType.ASSIGN_ID（应用赋值）。
-- ============================================================

DO $$
DECLARE
    start_val bigint;
BEGIN
    -- ── md_payment_method ──
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'md_payment_method' AND column_name = 'id' AND is_identity = 'NO'
    ) THEN
        SELECT COALESCE(MAX(id), 0) + 1 FROM md_payment_method INTO start_val;
        EXECUTE format(
            'ALTER TABLE md_payment_method ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH %s)',
            start_val
        );
    END IF;

    -- ── md_payment_channel ──
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'md_payment_channel' AND column_name = 'id' AND is_identity = 'NO'
    ) THEN
        SELECT COALESCE(MAX(id), 0) + 1 FROM md_payment_channel INTO start_val;
        EXECUTE format(
            'ALTER TABLE md_payment_channel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH %s)',
            start_val
        );
    END IF;
END $$;
