-- =====================================================================================
-- 阶段 3 · 批 1：`party` 扩到 22 列 + 建三张子表 + 回填
-- （方案：docs/PHASE-3-5-MIGRATION-PLAN-v1.md §3.2c 分批扩列表·批 1）
--
-- 【为什么先拆子表再扩列】A 组 27 列若全塞进 `party` ⇒ 41 列 ⇒ 超本仓"主表 ≤25 列"规范 ⇒
-- 那等于把 `biz_party` 的"上帝表"原样搬家，白折腾。故按 §3.2c：**先拆证件/银行/地址三张子表**，
-- 拆完 `party` 落 22 列，留出余量。
--
-- 【本批仍然"只加不删"】不改任何读路径、不动 `biz_party` 的任何一列（它的列在后续批次停写、最后才删）。
-- =====================================================================================

-- ─────────────── 1. party 扩列：14 → 22（只加"一个主体只有一个值"的属性） ───────────────
ALTER TABLE party ADD COLUMN IF NOT EXISTS company_full_name  VARCHAR(200);
ALTER TABLE party ADD COLUMN IF NOT EXISTS mnemonic_code     VARCHAR(64);   -- 助记码（快速检索）
ALTER TABLE party ADD COLUMN IF NOT EXISTS phone             VARCHAR(32);
ALTER TABLE party ADD COLUMN IF NOT EXISTS email             VARCHAR(128);
ALTER TABLE party ADD COLUMN IF NOT EXISTS website           VARCHAR(255);
ALTER TABLE party ADD COLUMN IF NOT EXISTS fax               VARCHAR(64);
ALTER TABLE party ADD COLUMN IF NOT EXISTS legal_person_phone VARCHAR(32);
ALTER TABLE party ADD COLUMN IF NOT EXISTS remark            VARCHAR(500);

-- ─────────────── 2. party_cert：证件（多张、带有效期） ───────────────
CREATE TABLE IF NOT EXISTS party_cert (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id     BIGINT       NOT NULL,
    cert_type    VARCHAR(32)  NOT NULL,        -- BUSINESS_LICENSE 营业执照 / TAX 税务登记 / 其他
    cert_no      VARCHAR(64),
    valid_from   DATE,
    valid_to     DATE,
    image        VARCHAR(255),                 -- 证件影像
    remark       VARCHAR(255),
    deleted      INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT, create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT, update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_party_cert_party ON party_cert (party_id) WHERE deleted = 0;
COMMENT ON TABLE party_cert IS '主体证件（**多张、带有效期**：执照/税务/许可…）；单列存不下第二张，故独立成表。';

-- ─────────────── 3. party_bank：银行（可多账户、可选默认） ───────────────
CREATE TABLE IF NOT EXISTS party_bank (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id     BIGINT       NOT NULL,
    bank_name    VARCHAR(200),
    bank_account VARCHAR(100),
    bank_address VARCHAR(255),
    is_default   INTEGER      NOT NULL DEFAULT 0,
    deleted      INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT, create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT, update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_party_bank_party ON party_bank (party_id) WHERE deleted = 0;
COMMENT ON TABLE party_bank IS '主体银行账户（**可多账户**，`is_default` 标默认）。';

-- ─────────────── 4. party_address：地址（按注册/营业/收货/发货分型） ───────────────
-- 形状**沿用 `biz_party_address`**（不另造一套）：
--   address_type 1 注册 / 2 营业 / 3 收货 / 4 发货
CREATE TABLE IF NOT EXISTS party_address (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id      BIGINT       NOT NULL,
    address_type  INTEGER      DEFAULT 1,
    contact_person VARCHAR(100),
    contact_phone  VARCHAR(50),
    country       VARCHAR(64),
    province      VARCHAR(64),
    city          VARCHAR(64),
    district      VARCHAR(64),
    detail_address VARCHAR(500),
    latitude      NUMERIC(10,6),
    longitude     NUMERIC(10,6),
    is_default    INTEGER      DEFAULT 0,
    remark        VARCHAR(255),
    deleted       INTEGER      NOT NULL DEFAULT 0,
    create_by     BIGINT, create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by     BIGINT, update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_party_address_party ON party_address (party_id) WHERE deleted = 0;
COMMENT ON TABLE party_address IS '主体地址（分型：注册/营业/收货/发货）；形状沿用 biz_party_address。';

-- ─────────────── 5. 回填（只搬"有值"的行；空值不造行） ───────────────
-- 5.1 主档属性（A 组里"单值"的部分）
UPDATE party p SET
    company_full_name   = b.company_full_name,
    mnemonic_code       = b.mnemonic_code,
    phone               = b.phone,
    email               = b.email,
    website             = b.website,
    fax                 = b.fax,
    legal_person_phone  = b.legal_person_phone,
    remark              = b.remark
FROM biz_party b
WHERE b.id = p.id AND b.deleted = 0;

-- 5.2 证件：执照（含到期日）与税务登记各一条，**只对有值的建行**
INSERT INTO party_cert (party_id, cert_type, cert_no, valid_to, remark)
SELECT b.id, 'BUSINESS_LICENSE', b.business_license, b.business_license_expiry, '由 biz_party 回填'
FROM biz_party b
WHERE b.deleted = 0 AND btrim(coalesce(b.business_license, '')) <> ''
  AND NOT EXISTS (SELECT 1 FROM party_cert c
                   WHERE c.party_id = b.id AND c.cert_type = 'BUSINESS_LICENSE' AND c.deleted = 0);

INSERT INTO party_cert (party_id, cert_type, cert_no, remark)
SELECT b.id, 'TAX', b.tax_number, '由 biz_party 回填'
FROM biz_party b
WHERE b.deleted = 0 AND btrim(coalesce(b.tax_number, '')) <> ''
  AND NOT EXISTS (SELECT 1 FROM party_cert c
                   WHERE c.party_id = b.id AND c.cert_type = 'TAX' AND c.deleted = 0);

-- 5.3 银行：有银行名或账号的建一条并标默认
INSERT INTO party_bank (party_id, bank_name, bank_account, bank_address, is_default)
SELECT b.id, b.bank_name, b.bank_account, b.bank_address, 1
FROM biz_party b
WHERE b.deleted = 0
  AND (btrim(coalesce(b.bank_name, '')) <> '' OR btrim(coalesce(b.bank_account, '')) <> '')
  AND NOT EXISTS (SELECT 1 FROM party_bank k WHERE k.party_id = b.id AND k.deleted = 0);

-- 5.4 地址：把 biz_party 上的地址字段落成"注册地址"一条（只对有地址信息的建行）
INSERT INTO party_address (party_id, address_type, province, city, district,
                           detail_address, latitude, longitude, is_default, remark)
SELECT b.id, 1, b.province, b.city, b.district, b.address, b.latitude, b.longitude, 1, '由 biz_party 回填'
FROM biz_party b
WHERE b.deleted = 0
  AND (btrim(coalesce(b.address, '')) <> '' OR btrim(coalesce(b.city, '')) <> ''
       OR btrim(coalesce(b.province, '')) <> '')
  AND NOT EXISTS (SELECT 1 FROM party_address a WHERE a.party_id = b.id AND a.deleted = 0);

-- ─────────────── 6. 自检 ───────────────
DO $$
DECLARE
    n_tables int;
    n_cols   int;
    n_party  int;
    n_orphan int;
BEGIN
    -- 6.1 三张子表齐备
    SELECT count(*) INTO n_tables FROM information_schema.tables
     WHERE table_schema = 'public' AND table_name IN ('party_cert', 'party_bank', 'party_address');
    IF n_tables <> 3 THEN
        RAISE EXCEPTION 'party_cert / party_bank / party_address 应三张都建好，实际 % 张', n_tables;
    END IF;

    -- 6.2 party 列数必须 ≤25（本仓"主表 ≤25 列"规范；本批后为 22）
    SELECT count(*) INTO n_cols FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = 'party';
    IF n_cols > 25 THEN
        RAISE EXCEPTION 'party 现有 % 列，超过"主表 ≤25 列"规范 —— 先拆子表再加列', n_cols;
    END IF;

    -- 6.3 本批**不改变主体数量**：party 行数不得为 0。
    --
    -- ⚠️ 这里**刻意不再断言"party 行数 == biz_party 未删行数"** —— 我第一版就是这么写的，
    --    而且它在真库上**必然失败**：那是"迁移那一刻的快照"，而 `biz_party` 之后会被
    --    正常业务/E2E 继续写入（实测：V11.497.0 之后又新建了 2 行，未删 19 → 21）。
    --    **迁移自检里不要写跨表行数相等的快照断言**（除非在同一事务里刚搬完）。
    --    真实的完整性约束是"子表不许悬空"（6.4），而不是"两张表行数永远相等"。
    --    两者的差额 = **迁移之后新建、尚未回填的主体**（在双写落地前只增不减），如实报出来。
    SELECT count(*) INTO n_party FROM party WHERE deleted = 0;
    IF n_party = 0 THEN
        RAISE EXCEPTION 'party 一行都没有，回填显然没跑';
    END IF;
    RAISE NOTICE 'party % 行 / biz_party 未删 % 行（差额 % = 迁移后新建、尚未回填的主体，双写落地前只增不减）',
        n_party, (SELECT count(*) FROM biz_party WHERE deleted = 0),
        (SELECT count(*) FROM biz_party b WHERE b.deleted = 0
           AND NOT EXISTS (SELECT 1 FROM party p WHERE p.id = b.id));

    -- 6.4 子表不许有悬空 party_id（三张一起查）
    SELECT count(*) INTO n_orphan FROM (
        SELECT c.party_id FROM party_cert c WHERE c.deleted = 0
         AND NOT EXISTS (SELECT 1 FROM party p WHERE p.id = c.party_id)
        UNION ALL
        SELECT k.party_id FROM party_bank k WHERE k.deleted = 0
         AND NOT EXISTS (SELECT 1 FROM party p WHERE p.id = k.party_id)
        UNION ALL
        SELECT a.party_id FROM party_address a WHERE a.deleted = 0
         AND NOT EXISTS (SELECT 1 FROM party p WHERE p.id = a.party_id)
    ) x;
    IF n_orphan > 0 THEN
        RAISE EXCEPTION '子表有 % 行 party_id 在 party 里找不到（悬空引用）', n_orphan;
    END IF;

    RAISE NOTICE '批 1 完成：party % 列 · party_cert % 行 · party_bank % 行 · party_address % 行',
        n_cols,
        (SELECT count(*) FROM party_cert WHERE deleted = 0),
        (SELECT count(*) FROM party_bank WHERE deleted = 0),
        (SELECT count(*) FROM party_address WHERE deleted = 0);
END $$;
