-- ============================================================
-- V11.3.0: 修复发票域 PaymentRecord 表名冲突
--
-- 背景：
--   erp-finance invoice 域 JPA 实体 PaymentRecord 原映射 payment_record，
--   与 core-payment 域的 payment_record（第三方支付回调结构，MyBatis-Plus）撞表。
--   两套实体语义完全不同，invoice 域匹配服务（InvoiceMatchingServiceImpl）
--   一旦读写必然 500。
--
-- 处置：
--   invoice 域实体改映射 invoice_payment_record，本脚本按实体定义建表。
--   core-payment 的 payment_record 不动。
-- ============================================================

CREATE TABLE IF NOT EXISTS invoice_payment_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_reference VARCHAR(50) NOT NULL,
    customer_id BIGINT,
    supplier_id BIGINT,
    invoice_id BIGINT NOT NULL,
    payment_amount DECIMAL(15,2) NOT NULL,
    matched_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    payment_status VARCHAR(20) NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    matching_type VARCHAR(20) NOT NULL,
    payment_date DATE NOT NULL,
    matched_date DATE,
    matched_at TIMESTAMP,
    matched_by BIGINT,
    matched_by_name VARCHAR(100),
    bank_transaction_id VARCHAR(100),
    bank_name VARCHAR(100),
    bank_account VARCHAR(50),
    payer_account VARCHAR(50),
    payee_account VARCHAR(50),
    currency_code VARCHAR(3) NOT NULL DEFAULT 'CNY',
    exchange_rate DECIMAL(10,6),
    original_amount DECIMAL(15,2),
    original_currency VARCHAR(3),
    matching_notes TEXT,
    verification_code VARCHAR(100),
    attachment_path VARCHAR(500),
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    verified_by BIGINT,
    verified_at TIMESTAMP,
    posted BOOLEAN NOT NULL DEFAULT FALSE,
    voucher_number VARCHAR(50),
    posted_at TIMESTAMP,
    posted_by BIGINT,
    refund_id BIGINT,
    is_credit_note BOOLEAN NOT NULL DEFAULT FALSE,
    credit_reason VARCHAR(500),
    source_system VARCHAR(50),
    source_system_id VARCHAR(100),
    batch_number VARCHAR(50),
    custom_field_1 VARCHAR(200),
    custom_field_2 VARCHAR(200),
    custom_field_3 VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    tenant_id VARCHAR(50),
    version INTEGER DEFAULT 0,
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(50),
    extensions TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_invoice_payment_record_ref ON invoice_payment_record(payment_reference);
CREATE INDEX IF NOT EXISTS idx_invoice_payment_record_invoice ON invoice_payment_record(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoice_payment_record_customer ON invoice_payment_record(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoice_payment_record_supplier ON invoice_payment_record(supplier_id);
CREATE INDEX IF NOT EXISTS idx_invoice_payment_record_status ON invoice_payment_record(payment_status);
CREATE INDEX IF NOT EXISTS idx_invoice_payment_record_batch ON invoice_payment_record(batch_number);
