-- 辅助核算类型/项目表主键对齐 finance 模块口径：改为 IDENTITY 自增
--
-- 背景（会计科目开发文档 P2 遗留缺陷续）：
--   V11.37.0 建表时 id 为 `BIGINT PRIMARY KEY`，没有自增（无 IDENTITY / 无 DEFAULT nextval），
--   而实体 FinanceAuxiliaryType / FinanceAuxiliaryItem 继承 finance BaseEntity
--   （@TableId(type = IdType.AUTO)）→ insert 不带 id，PG 报
--   「null value in column "id" ... violates not-null constraint」，
--   辅助核算类型/项目「新增」不可用（会计科目「核算项」下拉的数据源无法维护）。
--
--   finance_account / finance_account_subject / finance_voucher 等表均为 GENERATED ... AS IDENTITY，
--   本迁移对齐同一口径，不新建序列对象。
--
-- 幂等：仅当该表 id 列既非 identity、又无默认值时才转换；已有数据从 MAX(id)+1 续号。

DO $$
BEGIN
    -- ============ finance_auxiliary_type ============
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = 'finance_auxiliary_type'
                 AND column_name = 'id' AND is_identity = 'NO' AND column_default IS NULL) THEN
        ALTER TABLE finance_auxiliary_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        IF (SELECT COUNT(*) FROM finance_auxiliary_type) = 0 THEN
            PERFORM setval(pg_get_serial_sequence('finance_auxiliary_type', 'id'), 1, false);
        ELSE
            PERFORM setval(pg_get_serial_sequence('finance_auxiliary_type', 'id'),
                           (SELECT MAX(id) FROM finance_auxiliary_type));
        END IF;
    END IF;

    -- ============ finance_auxiliary_item ============
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = 'finance_auxiliary_item'
                 AND column_name = 'id' AND is_identity = 'NO' AND column_default IS NULL) THEN
        ALTER TABLE finance_auxiliary_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        IF (SELECT COUNT(*) FROM finance_auxiliary_item) = 0 THEN
            PERFORM setval(pg_get_serial_sequence('finance_auxiliary_item', 'id'), 1, false);
        ELSE
            PERFORM setval(pg_get_serial_sequence('finance_auxiliary_item', 'id'),
                           (SELECT MAX(id) FROM finance_auxiliary_item));
        END IF;
    END IF;
END $$;
