-- ============================================================
-- V11.5.0: 指标定义与指标值分表
--
-- 背景：
--   erp-observability 下两套实现共用 erp_business_metric：
--   - monitor 包（MyBatis-Plus）：写"指标值"时序数据（87万行，小写枚举码）
--   - metrics 包（JPA）：读写"指标定义"（calculation_formula/阈值，大写枚举名）
--   两者枚举大小写语义冲突，导致 JPA 读取 500、双方互相污染。
--
-- 处置：
--   metrics 包 BusinessMetric（指标定义）改映射新表 erp_metric_def。
--   erp_business_metric 归 monitor 包专用（指标值），数据不动。
-- ============================================================

CREATE TABLE IF NOT EXISTS erp_metric_def (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_code VARCHAR(64) NOT NULL,
    metric_name VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    metric_type VARCHAR(32) NOT NULL,
    period VARCHAR(16) NOT NULL,
    calculation_formula VARCHAR(1024),
    data_source VARCHAR(256),
    unit VARCHAR(32),
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    threshold_warning DOUBLE PRECISION,
    threshold_critical DOUBLE PRECISION,
    refresh_interval_seconds INTEGER,
    retention_days INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_metric_def_code ON erp_metric_def(metric_code);
CREATE INDEX IF NOT EXISTS idx_metric_def_type ON erp_metric_def(metric_type);
CREATE INDEX IF NOT EXISTS idx_metric_def_status ON erp_metric_def(status);
