-- 库存/商品域权限码种子（E-04，2026-09-21）
--
-- 【为什么】stock 域在 sys_permission 中没有任何码，而 E-01 要给该域控制器
--   补 @SaCheckPermission —— 没有码就直接补注解，会让这些接口对**所有非超管一律 403**
--   （本仓历史事故，铁律：先补种子后补注解）。
--
-- 【粒度】一码 = 一「资源 × 动作」，对齐既有约定（实测 PurchaseOrderController
--   16 端点 → 8 码）。本批：347 端点 → 202 码。
--
-- 【id 号段】权限码 102000 起（本模块独占槽位 slot=2）、角色关联 9520000 起。
--   9xxxx 段已被 V11.42x 系列的短块占满，故另开 100000 段；
--   各模块用不同槽位避免多迁移撞主键（本仓 sys_permission.id 无序列默认值）。
--
-- 【必须关联超管角色】本仓超管权限来自 sys_role_permission，不关联则平台管理员自己也会被拒。
-- =============================================================

INSERT INTO sys_permission (id, tenant_id, parent_id, deleted, create_time, update_time,
                            permission_name, permission_code, permission_type,
                            api_path, method, sort, visible, status)
SELECT v.id, 0, 0, 0, now(), now(), v.name, v.code, 3, v.api, v.method, v.sort, 1, 0
FROM (VALUES
 (102000, '库存/商品tag新增', 'mall:tag:create', '/api/erp/mall-tag', 'POST', 1200),
 (102001, '库存/商品tag删除', 'mall:tag:delete', '/api/erp/mall-tag/{id}', 'DELETE', 1201),
 (102002, '库存/商品tag导出', 'mall:tag:export', '/api/erp/mall-tag/export', 'GET', 1202),
 (102003, '库存/商品tag查询', 'mall:tag:list', '/api/erp/mall-tag/list', 'GET', 1203),
 (102004, '库存/商品tag编辑', 'mall:tag:update', '/api/erp/mall-tag/{id}', 'PUT', 1204),
 (102005, '库存/商品group-buy新增', 'marketing:group-buy:create', '/api/erp/marketing/group-buy', 'POST', 1205),
 (102006, '库存/商品group-buy详情', 'marketing:group-buy:detail', '/api/erp/marketing/group-buy/{id}', 'GET', 1206),
 (102007, '库存/商品group-buy查询', 'marketing:group-buy:list', '/api/erp/marketing/group-buy/page', 'GET', 1207),
 (102008, '库存/商品group-buy编辑', 'marketing:group-buy:update', '/api/erp/marketing/group-buy/{id}', 'PUT', 1208),
 (102009, '库存/商品group-buy查看', 'marketing:group-buy:view', '/api/erp/marketing/group-buy/{id}/participants', 'GET', 1209),
 (102010, '库存/商品image新增', 'md:image:create', '/api/erp/md/image/upload', 'POST', 1210),
 (102011, '库存/商品image删除', 'md:image:delete', '/api/erp/md/image/batch-delete', 'POST', 1211),
 (102012, '库存/商品image详情', 'md:image:detail', '/api/erp/md/image/product/{productId}', 'GET', 1212),
 (102013, '库存/商品image查询', 'md:image:list', '/api/erp/md/image/page', 'GET', 1213),
 (102014, '库存/商品image查看', 'md:image:view', '/api/erp/md/image/space-page', 'GET', 1214),
 (102015, '库存/商品product-price新增', 'md:product-price:create', '/api/erp/md/product-price/grade-discount/save', 'POST', 1215),
 (102016, '库存/商品product-price删除', 'md:product-price:delete', '/api/erp/md/product-price/grade-discount/{id}', 'DELETE', 1216),
 (102017, '库存/商品product-price导出', 'md:product-price:export', '/api/erp/md/product-price/export', 'GET', 1217),
 (102018, '库存/商品product-price导入', 'md:product-price:import', '/api/erp/md/product-price/level-price/import', 'POST', 1218),
 (102019, '库存/商品product-price查询', 'md:product-price:list', '/api/erp/md/product-price/page', 'GET', 1219),
 (102020, '库存/商品product-price编辑', 'md:product-price:update', '/api/erp/md/product-price/batch-modify', 'PUT', 1220),
 (102021, '库存/商品product-price查看', 'md:product-price:view', '/api/erp/md/product-price/brands', 'GET', 1221),
 (102022, '库存/商品attachments新增', 'product:attachments:create', '/api/erp/product/attachments', 'POST', 1222),
 (102023, '库存/商品attachments删除', 'product:attachments:delete', '/api/erp/product/attachments/{id}', 'DELETE', 1223),
 (102024, '库存/商品attachments详情', 'product:attachments:detail', '/api/erp/product/attachments/{productId}', 'GET', 1224),
 (102025, '库存/商品attributes新增', 'product:attributes:create', '/api/erp/product/attributes/defs', 'POST', 1225),
 (102026, '库存/商品attributes删除', 'product:attributes:delete', '/api/erp/product/attributes/defs/{id}', 'DELETE', 1226),
 (102027, '库存/商品attributes详情', 'product:attributes:detail', '/api/erp/product/attributes/values/{productId}', 'GET', 1227),
 (102028, '库存/商品attributes查询', 'product:attributes:list', '/api/erp/product/attributes/defs/{defId}/options', 'GET', 1228),
 (102029, '库存/商品attributes编辑', 'product:attributes:update', '/api/erp/product/attributes/defs/{id}', 'PUT', 1229),
 (102030, '库存/商品attributes查看', 'product:attributes:view', '/api/erp/product/attributes/defs', 'GET', 1230),
 (102031, '库存/商品barcodes新增', 'product:barcodes:create', '/api/erp/product/barcodes', 'POST', 1231),
 (102032, '库存/商品barcodes删除', 'product:barcodes:delete', '/api/erp/product/barcodes/{id}', 'DELETE', 1232),
 (102033, '库存/商品barcodes详情', 'product:barcodes:detail', '/api/erp/product/barcodes/{productId}', 'GET', 1233),
 (102034, '库存/商品barcodes导出', 'product:barcodes:export', '/api/erp/product/barcodes/export', 'GET', 1234),
 (102035, '库存/商品barcodes查询', 'product:barcodes:list', '/api/erp/product/barcodes/page', 'GET', 1235),
 (102036, '库存/商品barcodes编辑', 'product:barcodes:update', '/api/erp/product/barcodes/unit/{unitId}', 'PUT', 1236),
 (102037, '库存/商品brand新增', 'product:brand:create', '/api/erp/product-brand', 'POST', 1237),
 (102038, '库存/商品brand删除', 'product:brand:delete', '/api/erp/product-brand/{id}', 'DELETE', 1238),
 (102039, '库存/商品brand导出', 'product:brand:export', '/api/erp/product-brand/export', 'GET', 1239),
 (102040, '库存/商品brand查询', 'product:brand:list', '/api/erp/product-brand/page', 'GET', 1240),
 (102041, '库存/商品brand编辑', 'product:brand:update', '/api/erp/product-brand/{id}', 'PUT', 1241),
 (102042, '库存/商品category新增', 'product:category:create', '/api/erp/product-category', 'POST', 1242),
 (102043, '库存/商品category删除', 'product:category:delete', '/api/erp/product-category/{id}', 'DELETE', 1243),
 (102044, '库存/商品category详情', 'product:category:detail', '/api/erp/product-category/{id}', 'GET', 1244),
 (102045, '库存/商品category查询', 'product:category:list', '/api/erp/product-category/tree', 'GET', 1245),
 (102046, '库存/商品category编辑', 'product:category:update', '/api/erp/product-category/{id}', 'PUT', 1246),
 (102047, '库存/商品新增', 'product:create', '/api/erp/product', 'POST', 1247),
 (102048, '库存/商品删除', 'product:delete', '/api/erp/product/{id}', 'DELETE', 1248),
 (102049, '库存/商品详情', 'product:detail', '/api/erp/product/{id}', 'GET', 1249),
 (102050, '库存/商品导出', 'product:export', '/api/erp/product/export', 'GET', 1250),
 (102051, '库存/商品grade新增', 'product:grade:create', '/api/erp/product-grade', 'POST', 1251),
 (102052, '库存/商品grade删除', 'product:grade:delete', '/api/erp/product-grade/{id}', 'DELETE', 1252),
 (102053, '库存/商品grade详情', 'product:grade:detail', '/api/erp/product-grade/{id}', 'GET', 1253),
 (102054, '库存/商品grade查询', 'product:grade:list', '/api/erp/product-grade/list', 'GET', 1254),
 (102055, '库存/商品grade编辑', 'product:grade:update', '/api/erp/product-grade/{id}', 'PUT', 1255),
 (102056, '库存/商品导入', 'product:import', '/api/erp/product/import', 'POST', 1256),
 (102057, '库存/商品查询', 'product:list', '/api/erp/product/list', 'GET', 1257),
 (102058, '库存/商品location新增', 'product:location:create', '/api/erp/product-location/set', 'POST', 1258),
 (102059, '库存/商品location导出', 'product:location:export', '/api/erp/product-location/export', 'GET', 1259),
 (102060, '库存/商品location查询', 'product:location:list', '/api/erp/product-location/page', 'GET', 1260),
 (102061, '库存/商品related新增', 'product:related:create', '/api/erp/product/related', 'POST', 1261),
 (102062, '库存/商品related删除', 'product:related:delete', '/api/erp/product/related/{id}', 'DELETE', 1262),
 (102063, '库存/商品related详情', 'product:related:detail', '/api/erp/product/related/{productId}', 'GET', 1263),
 (102064, '库存/商品shield新增', 'product:shield:create', '/api/erp/product-shield', 'POST', 1264),
 (102065, '库存/商品shield查询', 'product:shield:list', '/api/erp/product-shield/page', 'GET', 1265),
 (102066, '库存/商品sku-rules新增', 'product:sku-rules:create', '/api/erp/product/sku-rules', 'POST', 1266),
 (102067, '库存/商品sku-rules删除', 'product:sku-rules:delete', '/api/erp/product/sku-rules/{id}', 'DELETE', 1267),
 (102068, '库存/商品sku-rules编辑', 'product:sku-rules:update', '/api/erp/product/sku-rules/{id}', 'PUT', 1268),
 (102069, '库存/商品sku-rules查看', 'product:sku-rules:view', '/api/erp/product/sku-rules', 'GET', 1269),
 (102070, '库存/商品unit-dict新增', 'product:unit-dict:create', '/api/erp/product-unit-dict', 'POST', 1270),
 (102071, '库存/商品unit-dict删除', 'product:unit-dict:delete', '/api/erp/product-unit-dict/{id}', 'DELETE', 1271),
 (102072, '库存/商品unit-dict导出', 'product:unit-dict:export', '/api/erp/product-unit-dict/export', 'GET', 1272),
 (102073, '库存/商品unit-dict查询', 'product:unit-dict:list', '/api/erp/product-unit-dict/page', 'GET', 1273),
 (102074, '库存/商品unit-dict编辑', 'product:unit-dict:update', '/api/erp/product-unit-dict/{id}', 'PUT', 1274),
 (102075, '库存/商品unit-group新增', 'product:unit-group:create', '/api/erp/product-unit-group', 'POST', 1275),
 (102076, '库存/商品unit-group删除', 'product:unit-group:delete', '/api/erp/product-unit-group/{id}', 'DELETE', 1276),
 (102077, '库存/商品unit-group详情', 'product:unit-group:detail', '/api/erp/product-unit-group/{id}', 'GET', 1277),
 (102078, '库存/商品unit-group导出', 'product:unit-group:export', '/api/erp/product-unit-group/export', 'GET', 1278),
 (102079, '库存/商品unit-group查询', 'product:unit-group:list', '/api/erp/product-unit-group/page', 'GET', 1279),
 (102080, '库存/商品unit-group编辑', 'product:unit-group:update', '/api/erp/product-unit-group/{id}', 'PUT', 1280),
 (102081, '库存/商品units新增', 'product:units:create', '/api/erp/product/units', 'POST', 1281),
 (102082, '库存/商品units删除', 'product:units:delete', '/api/erp/product/units/{id}', 'DELETE', 1282),
 (102083, '库存/商品units详情', 'product:units:detail', '/api/erp/product/units/{productId}', 'GET', 1283),
 (102084, '库存/商品units编辑', 'product:units:update', '/api/erp/product/units/{id}', 'PUT', 1284),
 (102085, '库存/商品编辑', 'product:update', '/api/erp/product/{id}', 'PUT', 1285),
 (102086, '库存/商品查看', 'product:view', '/api/erp/product/{id}/form', 'GET', 1286),
 (102087, '库存/商品alert-config新增', 'stock:alert-config:create', '/api/erp/stock-alert-config', 'POST', 1287),
 (102088, '库存/商品alert-config删除', 'stock:alert-config:delete', '/api/erp/stock-alert-config/{id}', 'DELETE', 1288),
 (102089, '库存/商品alert-config详情', 'stock:alert-config:detail', '/api/erp/stock-alert-config/{id}', 'GET', 1289),
 (102090, '库存/商品alert-config查询', 'stock:alert-config:list', '/api/erp/stock-alert-config/page', 'GET', 1290),
 (102091, '库存/商品alert-config编辑', 'stock:alert-config:update', '/api/erp/stock-alert-config/{id}', 'PUT', 1291),
 (102092, '库存/商品alert-config查看', 'stock:alert-config:view', '/api/erp/stock-alert-config/active', 'GET', 1292),
 (102093, '库存/商品alert查询', 'stock:alert:list', '/api/erp/stock-alert/page', 'GET', 1293),
 (102094, '库存/商品assemble审批', 'stock:assemble:approve', '/api/erp/stock/assemble/{id}/approve', 'POST', 1294),
 (102095, '库存/商品assemble新增', 'stock:assemble:create', '/api/erp/stock/assemble', 'POST', 1295),
 (102096, '库存/商品assemble详情', 'stock:assemble:detail', '/api/erp/stock/assemble/{id}', 'GET', 1296),
 (102097, '库存/商品assemble执行', 'stock:assemble:execute', '/api/erp/stock/assemble/{id}/execute', 'POST', 1297),
 (102098, '库存/商品assemble查询', 'stock:assemble:list', '/api/erp/stock/assemble/page', 'GET', 1298),
 (102099, '库存/商品assemble提交', 'stock:assemble:submit', '/api/erp/stock/assemble/{id}/submit', 'POST', 1299),
 (102100, '库存/商品assemble编辑', 'stock:assemble:update', '/api/erp/stock/assemble/{id}', 'PUT', 1300),
 (102101, '库存/商品bom新增', 'stock:bom:create', '/api/erp/stock/bom', 'POST', 1301),
 (102102, '库存/商品bom删除', 'stock:bom:delete', '/api/erp/stock/bom/{id}', 'DELETE', 1302),
 (102103, '库存/商品bom详情', 'stock:bom:detail', '/api/erp/stock/bom/{id}', 'GET', 1303),
 (102104, '库存/商品bom查询', 'stock:bom:list', '/api/erp/stock/bom/page', 'GET', 1304),
 (102105, '库存/商品bom编辑', 'stock:bom:update', '/api/erp/stock/bom/{id}', 'PUT', 1305),
 (102106, '库存/商品check审批', 'stock:check:approve', '/api/erp/stock/check/{id}/approve', 'POST', 1306),
 (102107, '库存/商品check校验', 'stock:check:check', '/api/erp/stock/check/{id}/items/{itemId}/check', 'POST', 1307),
 (102108, '库存/商品check新增', 'stock:check:create', '/api/erp/stock/check', 'POST', 1308),
 (102109, '库存/商品check删除', 'stock:check:delete', '/api/erp/stock/check/batch', 'DELETE', 1309),
 (102110, '库存/商品check详情', 'stock:check:detail', '/api/erp/stock/check/{id}', 'GET', 1310),
 (102111, '库存/商品check导出', 'stock:check:export', '/api/erp/stock/check/export', 'GET', 1311),
 (102112, '库存/商品check查询', 'stock:check:list', '/api/erp/stock/check/page', 'GET', 1312),
 (102113, '库存/商品check提交', 'stock:check:submit', '/api/erp/stock/check/{id}/submit', 'POST', 1313),
 (102114, '库存/商品check查看', 'stock:check:view', '/api/erp/stock/check/{id}/diff-items', 'GET', 1314),
 (102115, '库存/商品cost-adjust审批', 'stock:cost-adjust:approve', '/api/erp/stock/cost-adjust/{id}/approve', 'POST', 1315),
 (102116, '库存/商品cost-adjust新增', 'stock:cost-adjust:create', '/api/erp/stock/cost-adjust', 'POST', 1316),
 (102117, '库存/商品cost-adjust删除', 'stock:cost-adjust:delete', '/api/erp/stock/cost-adjust/{id}', 'DELETE', 1317),
 (102118, '库存/商品cost-adjust详情', 'stock:cost-adjust:detail', '/api/erp/stock/cost-adjust/{id}', 'GET', 1318),
 (102119, '库存/商品cost-adjust执行', 'stock:cost-adjust:execute', '/api/erp/stock/cost-adjust/{id}/execute', 'POST', 1319),
 (102120, '库存/商品cost-adjust查询', 'stock:cost-adjust:list', '/api/erp/stock/cost-adjust/page', 'GET', 1320),
 (102121, '库存/商品cost-adjust提交', 'stock:cost-adjust:submit', '/api/erp/stock/cost-adjust/{id}/submit', 'POST', 1321),
 (102122, '库存/商品cost-adjust编辑', 'stock:cost-adjust:update', '/api/erp/stock/cost-adjust/{id}', 'PUT', 1322),
 (102123, '库存/商品cost-adjust查看', 'stock:cost-adjust:view', '/api/erp/stock/cost-adjust/page-detail', 'GET', 1323),
 (102124, '库存/商品新增', 'stock:create', '/api/erp/stock/unfreeze', 'POST', 1324),
 (102125, '库存/商品damage新增', 'stock:damage:create', '/api/erp/stock/damage', 'POST', 1325),
 (102126, '库存/商品damage删除', 'stock:damage:delete', '/api/erp/stock/damage/{id}', 'DELETE', 1326),
 (102127, '库存/商品damage详情', 'stock:damage:detail', '/api/erp/stock/damage/{id}', 'GET', 1327),
 (102128, '库存/商品damage执行', 'stock:damage:execute', '/api/erp/stock/damage/{id}/execute', 'POST', 1328),
 (102129, '库存/商品damage查询', 'stock:damage:list', '/api/erp/stock/damage/page', 'GET', 1329),
 (102130, '库存/商品damage编辑', 'stock:damage:update', '/api/erp/stock/damage/{id}', 'PUT', 1330),
 (102131, '库存/商品damage查看', 'stock:damage:view', '/api/erp/stock/damage/page-detail', 'GET', 1331),
 (102132, '库存/商品详情', 'stock:detail', '/api/erp/stock/{productId}/{warehouseId}', 'GET', 1332),
 (102133, '库存/商品导出', 'stock:export', '/api/erp/stock/export', 'GET', 1333),
 (102134, '库存/商品冻结', 'stock:freeze', '/api/erp/stock/freeze', 'POST', 1334),
 (102135, '库存/商品in审批', 'stock:in:approve', '/api/erp/stock/in/{id}/approve', 'POST', 1335),
 (102136, '库存/商品in新增', 'stock:in:create', '/api/erp/stock/in', 'POST', 1336),
 (102137, '库存/商品in删除', 'stock:in:delete', '/api/erp/stock/in/{id}', 'DELETE', 1337),
 (102138, '库存/商品in详情', 'stock:in:detail', '/api/erp/stock/in/{id}', 'GET', 1338),
 (102139, '库存/商品in查询', 'stock:in:list', '/api/erp/stock/in/page', 'GET', 1339),
 (102140, '库存/商品in提交', 'stock:in:submit', '/api/erp/stock/in/{id}/submit', 'POST', 1340),
 (102141, '库存/商品in编辑', 'stock:in:update', '/api/erp/stock/in/{id}', 'PUT', 1341),
 (102142, '库存/商品in查看', 'stock:in:view', '/api/erp/stock/in/page-detail', 'GET', 1342),
 (102143, '库存/商品inventory-mode查询', 'stock:inventory-mode:list', '/api/erp/inventory-mode/options', 'GET', 1343),
 (102144, '库存/商品inventory-mode编辑', 'stock:inventory-mode:update', '/api/erp/inventory-mode', 'PUT', 1344),
 (102145, '库存/商品inventory-mode查看', 'stock:inventory-mode:view', '/api/erp/inventory-mode', 'GET', 1345),
 (102146, '库存/商品查询', 'stock:list', '/api/erp/stock/page', 'GET', 1346),
 (102147, '库存/商品out审批', 'stock:out:approve', '/api/erp/stock/out/{id}/approve', 'POST', 1347),
 (102148, '库存/商品out新增', 'stock:out:create', '/api/erp/stock/out', 'POST', 1348),
 (102149, '库存/商品out删除', 'stock:out:delete', '/api/erp/stock/out/{id}', 'DELETE', 1349),
 (102150, '库存/商品out详情', 'stock:out:detail', '/api/erp/stock/out/{id}', 'GET', 1350),
 (102151, '库存/商品out查询', 'stock:out:list', '/api/erp/stock/out/page', 'GET', 1351),
 (102152, '库存/商品out提交', 'stock:out:submit', '/api/erp/stock/out/{id}/submit', 'POST', 1352),
 (102153, '库存/商品out编辑', 'stock:out:update', '/api/erp/stock/out/{id}', 'PUT', 1353),
 (102154, '库存/商品out查看', 'stock:out:view', '/api/erp/stock/out/page-detail', 'GET', 1354),
 (102155, '库存/商品overflow审批', 'stock:overflow:approve', '/api/erp/stock/overflow/{id}/approve', 'POST', 1355),
 (102156, '库存/商品overflow新增', 'stock:overflow:create', '/api/erp/stock/overflow', 'POST', 1356),
 (102157, '库存/商品overflow删除', 'stock:overflow:delete', '/api/erp/stock/overflow/{id}', 'DELETE', 1357),
 (102158, '库存/商品overflow详情', 'stock:overflow:detail', '/api/erp/stock/overflow/{id}', 'GET', 1358),
 (102159, '库存/商品overflow执行', 'stock:overflow:execute', '/api/erp/stock/overflow/{id}/execute', 'POST', 1359),
 (102160, '库存/商品overflow查询', 'stock:overflow:list', '/api/erp/stock/overflow/page', 'GET', 1360),
 (102161, '库存/商品overflow提交', 'stock:overflow:submit', '/api/erp/stock/overflow/{id}/submit', 'POST', 1361),
 (102162, '库存/商品overflow编辑', 'stock:overflow:update', '/api/erp/stock/overflow/{id}', 'PUT', 1362),
 (102163, '库存/商品overflow查看', 'stock:overflow:view', '/api/erp/stock/overflow/page-detail', 'GET', 1363),
 (102164, '库存/商品replenishment新增', 'stock:replenishment:create', '/api/erp/stock/replenishment/generate', 'POST', 1364),
 (102165, '库存/商品replenishment查询', 'stock:replenishment:list', '/api/erp/stock/replenishment/list', 'GET', 1365),
 (102166, '库存/商品replenishment编辑', 'stock:replenishment:update', '/api/erp/stock/replenishment/{id}/ignore', 'PUT', 1366),
 (102167, '库存/商品split审批', 'stock:split:approve', '/api/erp/stock/split/{id}/approve', 'POST', 1367),
 (102168, '库存/商品split新增', 'stock:split:create', '/api/erp/stock/split', 'POST', 1368),
 (102169, '库存/商品split详情', 'stock:split:detail', '/api/erp/stock/split/{id}', 'GET', 1369),
 (102170, '库存/商品split执行', 'stock:split:execute', '/api/erp/stock/split/{id}/execute', 'POST', 1370),
 (102171, '库存/商品split查询', 'stock:split:list', '/api/erp/stock/split/page', 'GET', 1371),
 (102172, '库存/商品split提交', 'stock:split:submit', '/api/erp/stock/split/{id}/submit', 'POST', 1372),
 (102173, '库存/商品split编辑', 'stock:split:update', '/api/erp/stock/split/{id}', 'PUT', 1373),
 (102174, '库存/商品take新增', 'stock:take:create', '/api/erp/stock/take', 'POST', 1374),
 (102175, '库存/商品take删除', 'stock:take:delete', '/api/erp/stock/take/{id}', 'DELETE', 1375),
 (102176, '库存/商品take详情', 'stock:take:detail', '/api/erp/stock/take/{id}', 'GET', 1376),
 (102177, '库存/商品take查询', 'stock:take:list', '/api/erp/stock/take/page', 'GET', 1377),
 (102178, '库存/商品take编辑', 'stock:take:update', '/api/erp/stock/take/{id}', 'PUT', 1378),
 (102179, '库存/商品take查看', 'stock:take:view', '/api/erp/stock/take/page-detail', 'GET', 1379),
 (102180, '库存/商品transfer审批', 'stock:transfer:approve', '/api/erp/stock/transfer/{id}/approve', 'POST', 1380),
 (102181, '库存/商品transfer新增', 'stock:transfer:create', '/api/erp/stock/transfer', 'POST', 1381),
 (102182, '库存/商品transfer删除', 'stock:transfer:delete', '/api/erp/stock/transfer/{id}', 'DELETE', 1382),
 (102183, '库存/商品transfer详情', 'stock:transfer:detail', '/api/erp/stock/transfer/{id}', 'GET', 1383),
 (102184, '库存/商品transfer执行', 'stock:transfer:execute', '/api/erp/stock/transfer/{id}/execute', 'POST', 1384),
 (102185, '库存/商品transfer导出', 'stock:transfer:export', '/api/erp/stock/transfer/export', 'GET', 1385),
 (102186, '库存/商品transfer查询', 'stock:transfer:list', '/api/erp/stock/transfer/page', 'GET', 1386),
 (102187, '库存/商品transfer提交', 'stock:transfer:submit', '/api/erp/stock/transfer/{id}/submit', 'POST', 1387),
 (102188, '库存/商品transfer编辑', 'stock:transfer:update', '/api/erp/stock/transfer/{id}', 'PUT', 1388),
 (102189, '库存/商品transfer查看', 'stock:transfer:view', '/api/erp/stock/transfer/page-detail', 'GET', 1389),
 (102190, '库存/商品查看', 'stock:view', '/api/erp/stock/warehouses', 'GET', 1390),
 (102191, '库存/商品category新增', 'wms:category:create', '/api/erp/warehouse-category', 'POST', 1391),
 (102192, '库存/商品category删除', 'wms:category:delete', '/api/erp/warehouse-category/{id}', 'DELETE', 1392),
 (102193, '库存/商品category详情', 'wms:category:detail', '/api/erp/warehouse-category/{id}', 'GET', 1393),
 (102194, '库存/商品category查询', 'wms:category:list', '/api/erp/warehouse-category/tree', 'GET', 1394),
 (102195, '库存/商品category编辑', 'wms:category:update', '/api/erp/warehouse-category/{id}', 'PUT', 1395),
 (102196, '库存/商品新增', 'wms:create', '/api/erp/warehouse/save', 'POST', 1396),
 (102197, '库存/商品删除', 'wms:delete', '/api/erp/warehouse/{id}', 'DELETE', 1397),
 (102198, '库存/商品详情', 'wms:detail', '/api/erp/warehouse/{id}', 'GET', 1398),
 (102199, '库存/商品导出', 'wms:export', '/api/erp/warehouse/export', 'GET', 1399),
 (102200, '库存/商品查询', 'wms:list', '/api/erp/warehouse/list', 'GET', 1400),
 (102201, '库存/商品查看', 'wms:view', '/api/erp/warehouse/next-code', 'GET', 1401)
) AS v(id, name, code, api, method, sort)
WHERE NOT EXISTS (SELECT 1 FROM sys_permission p WHERE p.permission_code = v.code);

INSERT INTO sys_role_permission (id, role_id, permission_id, tenant_id, create_time)
SELECT 9520000 + row_number() OVER (ORDER BY p.id), 1, p.id, 1, now()
FROM sys_permission p
WHERE p.id BETWEEN 102000 AND 102202
  AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp
                  WHERE rp.role_id = 1 AND rp.permission_id = p.id);
