-- ============================================================
-- V11.6.0: 会计期间管理 + 月结（对标金蝶/用友总账月结）
--
-- 背景：
--   erp-finance 已有凭证(finance_voucher, fiscal_year/fiscal_period,
--   status=draft/audited/posted/reversed)与分类账(finance_ledger)，
--   但无会计期间表与月结机制，期间关闭靠约定无法控制。
--
-- 处置：
--   1) fin_accounting_period  会计期间表（tenant+period_code 唯一，
--      status: 1开启 / 0关闭）
--   2) fin_month_closing_log  月结/反月结操作日志（含检查结果快照）
--   3) 预置 2025-01 至 2026-12 开启状态期间（tenant_id=1）
-- ============================================================

CREATE TABLE IF NOT EXISTS fin_accounting_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    period_year INTEGER NOT NULL,
    period_month INTEGER NOT NULL,
    period_code VARCHAR(7) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    closed_by VARCHAR(64),
    closed_time TIMESTAMP,
    remark VARCHAR(500),
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_fin_period_tenant_code UNIQUE (tenant_id, period_code),
    CONSTRAINT ck_fin_period_month CHECK (period_month BETWEEN 1 AND 12)
);

COMMENT ON TABLE fin_accounting_period IS '会计期间表';
COMMENT ON COLUMN fin_accounting_period.period_code IS '期间编码，格式 yyyy-MM，如 2026-07';
COMMENT ON COLUMN fin_accounting_period.status IS '状态：1-开启 0-关闭（已月结）';

CREATE INDEX IF NOT EXISTS idx_fin_period_year ON fin_accounting_period(tenant_id, period_year);
CREATE INDEX IF NOT EXISTS idx_fin_period_status ON fin_accounting_period(tenant_id, status);

CREATE TABLE IF NOT EXISTS fin_month_closing_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    period_code VARCHAR(7) NOT NULL,
    action VARCHAR(16) NOT NULL,
    operator_id VARCHAR(64),
    operator_name VARCHAR(128),
    check_result TEXT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE fin_month_closing_log IS '月结操作日志';
COMMENT ON COLUMN fin_month_closing_log.action IS '操作类型：close-月结 reopen-反月结';
COMMENT ON COLUMN fin_month_closing_log.check_result IS '月结检查结果快照（JSON字符串）';

CREATE INDEX IF NOT EXISTS idx_fin_closing_log_period ON fin_month_closing_log(tenant_id, period_code);
CREATE INDEX IF NOT EXISTS idx_fin_closing_log_time ON fin_month_closing_log(create_time);

-- 预置 2025-01 至 2026-12 期间（开启状态），幂等
INSERT INTO fin_accounting_period (tenant_id, period_year, period_month, period_code, start_date, end_date, status, remark)
SELECT 1,
       y,
       m,
       y || '-' || lpad(m::text, 2, '0'),
       make_date(y, m, 1),
       (make_date(y, m, 1) + INTERVAL '1 month - 1 day')::date,
       1,
       '系统初始化期间'
FROM generate_series(2025, 2026) AS y
CROSS JOIN generate_series(1, 12) AS m
ON CONFLICT (tenant_id, period_code) DO NOTHING;
