-- ============================================================
-- V11.27.0: finance 域 12 张表 id 列补自增序列
--
-- 背景：
--   erp-finance 实体家族基类使用 @TableId(IdType.AUTO)（依赖数据库自增），
--   但 12 张 finance 表的 id 列均无序列默认值，insert 报
--   "null value in column id violates not-null constraint"
--   （业财直调应付记账 E2E 实测暴露）。
--   方案：id 列加 GENERATED BY DEFAULT AS IDENTITY——
--   同时兼容 IdType.AUTO（DB 生成）与 IdType.ASSIGN_ID（应用赋值）。
--   DO 块幂等：已是标识列的跳过（fin_accounting_period/fin_month_closing_log
--   在 V11.6.0 已正确创建）。
-- ============================================================

DO $$
DECLARE
    tbl text;
    tables text[] := ARRAY[
        'finance_payable', 'finance_receivable', 'finance_voucher', 'finance_voucher_item',
        'finance_ledger', 'finance_account', 'finance_account_subject', 'finance_report',
        'finance_tax_declaration', 'finance_transaction', 'fin_month_closing_log',
        'fin_accounting_period'
    ];
    start_val bigint;
BEGIN
    FOREACH tbl IN ARRAY tables LOOP
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'id' AND is_identity = 'NO'
        ) THEN
            -- 取当前最大值+1（空表为1，fin_accounting_period 为25）
            EXECUTE format('SELECT COALESCE(MAX(id), 0) + 1 FROM %I', tbl) INTO start_val;
            EXECUTE format('ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH %s)', tbl, start_val);
        END IF;
    END LOOP;
END $$;
