-- ============================================================================
-- V4.0.0__Create_Stock_Module_Tables.sql
-- 库存管理扩展模块：成本调价、报溢/报损、组装/拆分、BOM
-- ============================================================================

-- ── 1. 成本调价单 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS erp_stock_cost_adjust (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
    adjust_no VARCHAR(64) NOT NULL COMMENT '调价单号',
    adjust_type TINYINT NOT NULL DEFAULT 1 COMMENT '调价类型 1-移动加权 2-全月平均 3-个别计价',
    adjust_date DATE NOT NULL COMMENT '调价日期',
    warehouse_id BIGINT COMMENT '仓库ID',
    warehouse_name VARCHAR(100) COMMENT '仓库名称',
    total_adjust_amount DECIMAL(18,2) DEFAULT 0 COMMENT '调价总金额',
    total_items INT DEFAULT 0 COMMENT '调价商品数',
    reason_type VARCHAR(32) COMMENT '调价原因类型: market/supplier/exchange/other',
    reason_desc VARCHAR(500) COMMENT '调价原因说明',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态 0-草稿 1-待审批 2-已审批 3-已执行 4-已拒绝 5-已取消',
    applicant_id BIGINT COMMENT '申请人ID',
    applicant_name VARCHAR(50) COMMENT '申请人',
    apply_time DATETIME COMMENT '申请时间',
    approved_by BIGINT COMMENT '审批人ID',
    approved_time DATETIME COMMENT '审批时间',
    approved_note VARCHAR(200) COMMENT '审批意见',
    executed_by BIGINT COMMENT '执行人ID',
    executed_time DATETIME COMMENT '执行时间',
    remark VARCHAR(500) COMMENT '备注',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT COMMENT '创建人',
    update_by BIGINT COMMENT '更新人',
    version_no INT DEFAULT 0 COMMENT '乐观锁',
    INDEX idx_tenant_status (tenant_id, status),
    INDEX idx_adjust_no (adjust_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='成本调价单';

CREATE TABLE IF NOT EXISTS erp_stock_cost_adjust_item (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
    adjust_id BIGINT NOT NULL COMMENT '调价单ID',
    product_id BIGINT NOT NULL COMMENT '产品ID',
    product_code VARCHAR(64) COMMENT '产品编码',
    product_name VARCHAR(200) COMMENT '产品名称',
    product_spec VARCHAR(100) COMMENT '规格',
    product_unit VARCHAR(20) COMMENT '单位',
    warehouse_id BIGINT COMMENT '仓库ID',
    batch_no VARCHAR(64) COMMENT '批次号',
    current_quantity DECIMAL(18,4) DEFAULT 0 COMMENT '当前库存数量',
    old_cost DECIMAL(18,2) DEFAULT 0 COMMENT '调前成本价',
    new_cost DECIMAL(18,2) DEFAULT 0 COMMENT '调后成本价',
    diff_amount DECIMAL(18,2) DEFAULT 0 COMMENT '调价差额 = (new_cost - old_cost) * quantity',
    remark VARCHAR(200) COMMENT '备注',
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_adjust_id (adjust_id),
    INDEX idx_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='成本调价明细';

-- ── 2. 报溢单 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS erp_stock_overflow (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
    overflow_no VARCHAR(64) NOT NULL COMMENT '报溢单号',
    overflow_date DATE NOT NULL COMMENT '报溢日期',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    warehouse_name VARCHAR(100) COMMENT '仓库名称',
    location_id BIGINT COMMENT '货位ID',
    location_code VARCHAR(64) COMMENT '货位编码',
    total_quantity DECIMAL(18,4) DEFAULT 0 COMMENT '报溢总数量',
    total_amount DECIMAL(18,2) DEFAULT 0 COMMENT '报溢总金额',
    total_items INT DEFAULT 0 COMMENT '报溢商品数',
    source_type VARCHAR(32) COMMENT '来源类型: check_discover/discover/other',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态 0-草稿 1-待审批 2-已审核 3-已入库 4-已拒绝 5-已取消',
    applicant_id BIGINT COMMENT '申请人ID',
    applicant_name VARCHAR(50) COMMENT '申请人',
    apply_time DATETIME COMMENT '申请时间',
    approved_by BIGINT COMMENT '审批人ID',
    approved_time DATETIME COMMENT '审批时间',
    approved_note VARCHAR(200) COMMENT '审批意见',
    executed_by BIGINT COMMENT '执行人ID',
    executed_time DATETIME COMMENT '执行时间(入库时间)',
    remark VARCHAR(500) COMMENT '备注',
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    INDEX idx_tenant_status (tenant_id, status),
    INDEX idx_overflow_no (overflow_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报溢单';

CREATE TABLE IF NOT EXISTS erp_stock_overflow_item (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    overflow_id BIGINT NOT NULL COMMENT '报溢单ID',
    product_id BIGINT NOT NULL COMMENT '产品ID',
    product_code VARCHAR(64) COMMENT '产品编码',
    product_name VARCHAR(200) COMMENT '产品名称',
    product_spec VARCHAR(100) COMMENT '规格',
    product_unit VARCHAR(20) COMMENT '单位',
    quantity DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '报溢数量',
    unit_cost DECIMAL(18,2) DEFAULT 0 COMMENT '入库单价',
    amount DECIMAL(18,2) DEFAULT 0 COMMENT '金额',
    batch_no VARCHAR(64) COMMENT '批次号',
    production_date DATE COMMENT '生产日期',
    remark VARCHAR(200) COMMENT '备注',
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_overflow_id (overflow_id),
    INDEX idx_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报溢明细';

-- ── 3. 报损单 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS erp_stock_damage (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
    damage_no VARCHAR(64) NOT NULL COMMENT '报损单号',
    damage_date DATE NOT NULL COMMENT '报损日期',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    warehouse_name VARCHAR(100) COMMENT '仓库名称',
    location_id BIGINT COMMENT '货位ID',
    location_code VARCHAR(64) COMMENT '货位编码',
    total_quantity DECIMAL(18,4) DEFAULT 0 COMMENT '报损总数量',
    total_amount DECIMAL(18,2) DEFAULT 0 COMMENT '报损总金额',
    total_items INT DEFAULT 0 COMMENT '报损商品数',
    damage_cause TINYINT NOT NULL DEFAULT 1 COMMENT '报损原因 1-自然损耗 2-人为损坏 3-过期 4-质量异常 5-其他',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态 0-草稿 1-待审批 2-已审核 3-已出库 4-已拒绝 5-已取消',
    applicant_id BIGINT COMMENT '申请人ID',
    applicant_name VARCHAR(50) COMMENT '申请人',
    apply_time DATETIME COMMENT '申请时间',
    approved_by BIGINT COMMENT '审批人ID',
    approved_time DATETIME COMMENT '审批时间',
    approved_note VARCHAR(200) COMMENT '审批意见',
    executed_by BIGINT COMMENT '执行人ID',
    executed_time DATETIME COMMENT '执行时间(出库时间)',
    remark VARCHAR(500) COMMENT '备注',
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    INDEX idx_tenant_status (tenant_id, status),
    INDEX idx_damage_no (damage_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报损单';

CREATE TABLE IF NOT EXISTS erp_stock_damage_item (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    damage_id BIGINT NOT NULL COMMENT '报损单ID',
    product_id BIGINT NOT NULL COMMENT '产品ID',
    product_code VARCHAR(64) COMMENT '产品编码',
    product_name VARCHAR(200) COMMENT '产品名称',
    product_spec VARCHAR(100) COMMENT '规格',
    product_unit VARCHAR(20) COMMENT '单位',
    quantity DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '报损数量',
    unit_cost DECIMAL(18,2) DEFAULT 0 COMMENT '出库单价',
    amount DECIMAL(18,2) DEFAULT 0 COMMENT '金额',
    batch_no VARCHAR(64) COMMENT '批次号',
    production_date DATE COMMENT '生产日期',
    remark VARCHAR(200) COMMENT '备注',
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_damage_id (damage_id),
    INDEX idx_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报损明细';

-- ── 4. BOM 物料清单 ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS erp_stock_bom (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
    bom_no VARCHAR(64) NOT NULL COMMENT 'BOM编号',
    bom_name VARCHAR(200) COMMENT 'BOM名称',
    product_id BIGINT NOT NULL COMMENT '成品产品ID',
    product_code VARCHAR(64) COMMENT '成品编码',
    product_name VARCHAR(200) COMMENT '成品名称',
    product_spec VARCHAR(100) COMMENT '成品规格',
    product_unit VARCHAR(20) COMMENT '成品单位',
    output_quantity DECIMAL(18,4) DEFAULT 1 COMMENT '产出数量(成品数量)',
    total_cost DECIMAL(18,2) DEFAULT 0 COMMENT 'BOM总成本',
    bom_type TINYINT DEFAULT 1 COMMENT '类型 1-组装BOM 2-拆分BOM 3-通用',
    status TINYINT DEFAULT 1 COMMENT '状态 0-停用 1-启用',
    effective_date DATE COMMENT '生效日期',
    expire_date DATE COMMENT '失效日期',
    remark VARCHAR(500) COMMENT '备注',
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    INDEX idx_tenant (tenant_id),
    INDEX idx_product (product_id),
    INDEX idx_bom_no (bom_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='BOM物料清单';

CREATE TABLE IF NOT EXISTS erp_stock_bom_item (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
    bom_id BIGINT NOT NULL COMMENT 'BOM ID',
    product_id BIGINT NOT NULL COMMENT '子件产品ID',
    product_code VARCHAR(64) COMMENT '子件编码',
    product_name VARCHAR(200) COMMENT '子件名称',
    product_spec VARCHAR(100) COMMENT '子件规格',
    product_unit VARCHAR(20) COMMENT '子件单位',
    quantity DECIMAL(18,4) NOT NULL DEFAULT 1 COMMENT '子件用量',
    unit_cost DECIMAL(18,2) DEFAULT 0 COMMENT '子件单价',
    cost DECIMAL(18,2) DEFAULT 0 COMMENT '子件成本 = quantity * unit_cost',
    wastage_rate DECIMAL(10,6) DEFAULT 0 COMMENT '损耗率',
    remark VARCHAR(200) COMMENT '备注',
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_bom_id (bom_id),
    INDEX idx_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='BOM物料清单明细';

-- ── 5. 组装单 ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS erp_stock_assemble (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
    assemble_no VARCHAR(64) NOT NULL COMMENT '组装单号',
    assemble_date DATE NOT NULL COMMENT '组装日期',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    warehouse_name VARCHAR(100) COMMENT '仓库名称',
    in_warehouse_id BIGINT COMMENT '成品入库仓库ID',
    in_warehouse_name VARCHAR(100) COMMENT '成品入库仓库名称',
    out_warehouse_id BIGINT COMMENT '原料出库仓库ID',
    out_warehouse_name VARCHAR(100) COMMENT '原料出库仓库名称',
    handler_name VARCHAR(50) COMMENT '经手人',
    produce_unit VARCHAR(100) COMMENT '生产单位',
    print_count INT DEFAULT 0 COMMENT '打印次数',
    print_records VARCHAR(500) COMMENT '打印记录',
    bom_id BIGINT COMMENT 'BOM ID',
    bom_no VARCHAR(64) COMMENT 'BOM编号',
    bom_name VARCHAR(200) COMMENT 'BOM名称',
    product_id BIGINT NOT NULL COMMENT '成品产品ID',
    product_code VARCHAR(64) COMMENT '成品编码',
    product_name VARCHAR(200) COMMENT '成品名称',
    product_spec VARCHAR(100) COMMENT '成品规格',
    product_unit VARCHAR(20) COMMENT '成品单位',
    assemble_quantity DECIMAL(18,4) NOT NULL DEFAULT 1 COMMENT '组装数量',
    sub_total_cost DECIMAL(18,2) DEFAULT 0 COMMENT '子件总成本',
    assemble_fee DECIMAL(18,2) DEFAULT 0 COMMENT '组装费用',
    total_cost DECIMAL(18,2) DEFAULT 0 COMMENT '总成本 = sub_total_cost + assemble_fee',
    output_quantity DECIMAL(18,4) DEFAULT 0 COMMENT '产出数量',
    total_items INT DEFAULT 0 COMMENT '子件数量',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态 0-草稿 1-待审批 2-已审核 3-已完成 4-已拒绝 5-已取消',
    applicant_id BIGINT,
    applicant_name VARCHAR(50),
    apply_time DATETIME,
    approved_by BIGINT,
    approved_time DATETIME,
    approved_note VARCHAR(200),
    executed_by BIGINT,
    executed_time DATETIME COMMENT '执行时间(子件出库+成品入库)',
    remark VARCHAR(500),
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    INDEX idx_tenant (tenant_id),
    INDEX idx_assemble_no (assemble_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='组装单';

CREATE TABLE IF NOT EXISTS erp_stock_assemble_item (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
    assemble_id BIGINT NOT NULL COMMENT '组装单ID',
    product_id BIGINT NOT NULL COMMENT '子件产品ID',
    product_code VARCHAR(64) COMMENT '子件编码',
    product_name VARCHAR(200) COMMENT '子件名称',
    product_spec VARCHAR(100) COMMENT '子件规格',
    product_unit VARCHAR(20) COMMENT '子件单位',
    quantity DECIMAL(18,4) NOT NULL DEFAULT 1 COMMENT '子件数量(按BOM计算)',
    unit_cost DECIMAL(18,2) DEFAULT 0 COMMENT '子件单价(实际出库成本)',
    cost DECIMAL(18,2) DEFAULT 0 COMMENT '子件成本 = quantity * unit_cost',
    remark VARCHAR(200),
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_assemble_id (assemble_id),
    INDEX idx_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='组装单明细(子件)';

-- ── 6. 拆分单 ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS erp_stock_split (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
    split_no VARCHAR(64) NOT NULL COMMENT '拆分单号',
    split_date DATE NOT NULL COMMENT '拆分日期',
    warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    warehouse_name VARCHAR(100) COMMENT '仓库名称',
    in_warehouse_id BIGINT COMMENT '原料入库仓库ID',
    in_warehouse_name VARCHAR(100) COMMENT '原料入库仓库名称',
    out_warehouse_id BIGINT COMMENT '成品出库仓库ID',
    out_warehouse_name VARCHAR(100) COMMENT '成品出库仓库名称',
    handler_name VARCHAR(50) COMMENT '经手人',
    print_count INT DEFAULT 0 COMMENT '打印次数',
    print_records VARCHAR(500) COMMENT '打印记录',
    bom_id BIGINT COMMENT 'BOM ID',
    bom_no VARCHAR(64) COMMENT 'BOM编号',
    bom_name VARCHAR(200) COMMENT 'BOM名称',
    product_id BIGINT NOT NULL COMMENT '成品产品ID(被拆分)',
    product_code VARCHAR(64) COMMENT '成品编码',
    product_name VARCHAR(200) COMMENT '成品名称',
    product_spec VARCHAR(100) COMMENT '成品规格',
    product_unit VARCHAR(20) COMMENT '成品单位',
    split_quantity DECIMAL(18,4) NOT NULL DEFAULT 1 COMMENT '拆分数量',
    output_total_cost DECIMAL(18,2) DEFAULT 0 COMMENT '成品出库总成本',
    sub_total_cost DECIMAL(18,2) DEFAULT 0 COMMENT '子件入库总成本',
    total_items INT DEFAULT 0 COMMENT '子件数量',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态 0-草稿 1-待审批 2-已审核 3-已完成 4-已拒绝 5-已取消',
    applicant_id BIGINT,
    applicant_name VARCHAR(50),
    apply_time DATETIME,
    approved_by BIGINT,
    approved_time DATETIME,
    approved_note VARCHAR(200),
    executed_by BIGINT,
    executed_time DATETIME,
    remark VARCHAR(500),
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    INDEX idx_tenant (tenant_id),
    INDEX idx_split_no (split_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='拆分单';

CREATE TABLE IF NOT EXISTS erp_stock_split_item (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
    split_id BIGINT NOT NULL COMMENT '拆分单ID',
    product_id BIGINT NOT NULL COMMENT '子件产品ID',
    product_code VARCHAR(64) COMMENT '子件编码',
    product_name VARCHAR(200) COMMENT '子件名称',
    product_spec VARCHAR(100) COMMENT '子件规格',
    product_unit VARCHAR(20) COMMENT '子件单位',
    quantity DECIMAL(18,4) NOT NULL DEFAULT 1 COMMENT '子件数量',
    unit_cost DECIMAL(18,2) DEFAULT 0 COMMENT '子件入库单价(分摊成本)',
    cost DECIMAL(18,2) DEFAULT 0 COMMENT '子件成本 = quantity * unit_cost',
    allocation_ratio DECIMAL(10,6) DEFAULT 0 COMMENT '分摊比例',
    remark VARCHAR(200),
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_split_id (split_id),
    INDEX idx_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='拆分单明细(子件)';
