/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BannerSwiper: typeof import('./src/components/home/BannerSwiper.vue')['default']
    CategoryNav: typeof import('./src/components/home/CategoryNav.vue')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    ProductGrid: typeof import('./src/components/product/ProductGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/common/SearchBar.vue')['default']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
  }
}
