server:
  port: 5657

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb?currentSchema=dms
    username: devuser
    password: devuser123
  jpa:
    show-sql: true

logging:
  level:
    cn.aiedge.dms: DEBUG
    com.baomidou.mybatisplus: DEBUG

dms:
  erp:
    base-url: http://localhost:8080/api/erp
  wms:
    base-url: http://localhost:8081/api/wms
