/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContractForm: typeof import('./src/components/ContractForm.vue')['default']
    InvoiceForm: typeof import('./src/components/InvoiceForm.vue')['default']
    QuotationForm: typeof import('./src/components/QuotationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
